name: solar_annotate
channels:
  - conda-forge
dependencies:
  - matplotlib>=3.7.2
  - astropy>=5.3.1
  - numpy>=1.25.1
  - scipy>=1.11.1
  - scikit-image>=0.21.0
  - pillow>=10.0.0
  - sunpy>=5.0.0
  - lxml>=4.9.3
  - reproject>=0.11.0
  - zeep>=4.2.1
  - drms>=0.6.4
  - pip
  - pip:
      - pyqt5>=5.15.9
      - goes-solar-retriever
